project_id = "livrank"

[db]
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/confirm"]

[auth.email]
enable_signup = true
enable_confirmations = false
